<div style="margin-left: 10px; font-family: arial, sans-serif; font-size: 14px; font-weight: bold; line-height: 2em;">

<a href="/node/add/blog">Blog (will go in News section)</a><br><br>

<a href="/node/add/promotion">Promotion</a><br><br>

<a href="/node/add/testimonial">Testimonial</a><br><br>


<div style="display: inline; width: 120px; margin-right: 10px;">
	<a href="/node/add/services">Service</a>
</div>
<div style="float: right;display: inline-block; position: relative; width: 795px;">For instructions on how to Add/Edit items to the service menu, please refer to <a href="sites/default/files/menu_how_to.docx">Menu How To</a></div>
<br><br>


<div style="display: inline; width: 120px; margin-right: 10px;"><a href="/node/add/photo-gallery">Photo Gallery</a></div><br><br>

<div style="margin-bottom: 25px;"><div style="display: inline; width: 120px; margin-right: 10px;"><a href="/admin/structure/nivo-slider">Front Page Slider</a></div><div style="float: right;display: inline-block; position: relative; width: 795px;">To add an image, under "Upload a New Image", click Choose File, and choose an image.  Then scroll down and press save configuration.  To delete an image, click on the image in the image list, scroll down, then press "delete slide", then press save configuration.  </div></div><br><br>


<div style="margin-bottom: 25px;">
<div style="display: inline; width: 120px; margin-right: 10px;">
	<a href="/node/add/video">Videos</a>
</div>
<div style="float: right;display: inline-block; position: relative; width: 795px;">
Add a video for the Photos/Videos page.  Provide a title, which will appear below the video in the gallery.  Paste the url of the YouTube video into the 'Video URL' field.
</div></div>
<br><br>


<div style="display: inline; width: 120px; margin-right: 10px;">
	<a href="/node/168/webform-results/table">Webform Results</a>
</div>
<div style="float: right;display: inline-block; position: relative; width: 795px;">
These are the results of the 'Sign up for Free Giveaways' form.  If you want to download the results to an excel file, press download in the tab at the top, then choose your export format. 
</div>
<br>


</div>