<head>
		<meta http-equiv="content-type" content="text/html;charset=iso-8859-1">
		<meta name="generator" content="Adobe GoLive">
		<title>Jeffrey LaMorte - Purchase Gift Certificate</title>
		
		<SCRIPT LANGUAGE="JavaScript">
			<!-- Original:  Cyanide_7 (leo7278@hotmail.com) -->
			<!-- Web Site:  http://www7.ewebcity.com/cyanide7 -->
			
			<!-- This script and many more are available free online at -->
			<!-- The JavaScript Source!! http://javascript.internet.com -->
			
			<!-- Begin
			// test variables
			var myHeight = 600;
			var myWidth = 800;
			var isResizable = true;
			
			function createTarget(form) {
				_target = form.target;
				_colon = _target.indexOf(":");
				if(_colon != -1) {
					form.target = _target.substring(0,_colon);
					form.args = _target.substring(_colon+1);
				} else if(typeof(form.args)=="undefined") {
					form.args = "";
				}
				if(form.args.indexOf("{")!=-1) {
					_args = form.args.split("{");
					form.args = _args[0];
					for(var i = 1; i < _args.length;i++) {
						_args[i] = _args[i].split("}");
						form.args += eval(_args[i][0]) + _args[i][1];
				  	 }
				}
				
				form.args = form.args.replace(/ /g,"");
				_win = window.open('',form.target,form.args);
				if(typeof(focus)=="function")
					_win.focus();
					return true;
			}
			//  End -->
			</script>
	</head>
	
<h2 style="background-color: transparent; padding-left: 0px !important; margin-bottom: 10px;">Gift Cards</h2>	
For special occasions or for just brightening someone's day, Jeffrey LaMorte Salon and Day Spa gift cards are available for purchase in any dollar amount. These gift cards never expire and can be used towards the purchase of salon/spa products and services at any Jeffrey LaMorte location. They are not, however, redeemable for cash and cannot be used for salon/spa gratuity. Gift cards can be purchased at any of our three locations or online by using the form below. The actual cards are then mailed to clients after payment information is submitted.	

<div style="width: 100%;">
<div style="width: 30%; margin: 0px auto;">
<form action="https://www.paypal.com/cgi-bin/webscr" method="post" target="foobar:width={myWidth},
         height={myHeight},
         scrollbars,
         {(isResizable)?'resizable':''},
         status"
onSubmit="return createTarget(this);">
										<br>
										<input type="hidden" name="cmd" value="_s-xclick">
<input type="hidden" name="hosted_button_id" value="75F6V7B6AAK3L">
<table>
<tr><td style="text-align: center;"><input type="hidden" name="on0" value="Gift Certificate"><font size="1" style="text-align: center;" color="black" face="Arial, Helvetica, Verdana">Select the amount of the Gift Certificate you would like to purchase.<br>
													</font></td></tr><tr><td style="text-align: center;"><select name="os0">
	<option value="25">25 $25.00</option>
	<option value="50">50 $50.00</option>
	<option value="75">75 $75.00</option>
	<option value="100">100 $100.00</option>
	<option value="150">150 $150.00</option>
	<option value="200">200 $200.00</option>
	<option value="250">250 $250.00</option>
	<option value="300">300 $300.00</option>
	<option value="350">350 $350.00</option>
	<option value="400">400 $400.00</option>
</select> </td></tr>
</table>
										<br>
										<input type="hidden" name="currency_code" value="USD">
								<div style="text-align: center;">
										<input type="image" src="https://www.paypal.com/en_US/i/btn/btn_buynowCC_LG.gif" border="0" name="submit" alt="PayPal - The safer, easier way to pay online!" target="_blank">
								</div>		
										<br>
										<br>
										
<img alt="" border="0" src="https://www.paypal.com/en_US/i/scr/pixel.gif" width="1" height="1">
</form>
</div>
</div>